platform :ios, '13.0'

target 'Evaluator-Video-Test' do
  use_frameworks!

  pod 'TensorFlowLiteSwift'
  pod 'TensorFlowLiteSwift/Metal'
  pod 'TensorFlowLiteSwift/CoreML'

  # Hand & pose landmarker (.task models) used by CombinedLandmarkerHelper.swift
  pod 'MediaPipeTasksVision'

end
